language: ruby
group: travis_lts
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1
  - jruby-9.2
matrix:
  allow_failures:
  - rvm: jruby-9.2
before_install:
  - gem update bundler
